[package]
name = "glotaran_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glotaran_conv_lib = { version = "0.1.0", path = "../glotaran_conv_lib" }
